Online_book_shopping/Online_book_shopping/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Online_book_shopping.Models;

namespace Online_book_shopping.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private BookShoppingDBContext db = new BookShoppingDBContext();

        // GET: Transactions
        [Authorize(Roles = "Customer")]
        public ActionResult Index()
        {

            var currentUser = db.Users
                .FirstOrDefault(u => u.UserName == User.Identity.Name);
            var transactions = db.Transactions
                .Include(t => t.Payment)
                .Where(t => t.Customer.Id == currentUser.Id && t.isDeleted == false)
                .ToList();
            var records = db.Records
                .Include(r => r.Book)
                .Include(r => r.Transaction)
                .Where(c => c.Transaction.Customer.Id == currentUser.Id)
                .ToList();
            return View(transactions.ToList());
        }

        // GET: Transactions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Transaction transaction = 
                db.Transactions
                //.Include(t => t.Payment)
                .Include(t => t.Recordes)
                .FirstOrDefault(t => t.TransactionID == id);

            var records = db.Records
                .Include(r => r.Book)
                .Where(c => c.Transaction.TransactionID == transaction.TransactionID)
                .ToList();

            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // GET: Transactions/Create
        public ActionResult Create()
        {
            ViewBag.TransactionID = new SelectList(db.Payments, "PaymentID", "PaymentID");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TransactionID,ShippingStatus,Total")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TransactionID = new SelectList(db.Payments, "PaymentID", "PaymentID", transaction.TransactionID);
            return View(transaction);
        }

        // GET: Transactions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            ViewBag.TransactionID = new SelectList(db.Payments, "PaymentID", "PaymentID", transaction.TransactionID);
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TransactionID,ShippingStatus,Total")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(transaction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TransactionID = new SelectList(db.Payments, "PaymentID", "PaymentID", transaction.TransactionID);
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Transaction transaction = db.Transactions
                .Include(t => t.Payment)
                .FirstOrDefault(t => t.TransactionID == id);

            var records = db.Records
                .Include(r => r.Book)
                .Include(r => r.Transaction)
                .Where(c => c.Transaction.TransactionID == transaction.TransactionID)
                .ToList();

            transaction.isDeleted = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // POST: Transactions/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Confirmed(Cart cart)
        {
            Console.WriteLine();

            var user = db.Users
                .OfType<Customer>()
                .Include(u => u.Cart)
                .Include( u => u.Addresses)
                .First(u => u.UserName == User.Identity.Name);

            Transaction transaction = new Transaction()
            {
                Address = user.Addresses.First(),
                Customer = user,
                Payment = new Payment()
            };

            transaction.Recordes = db.Records.Include(r => r.Book).Where(r => r.CartID == cart.CartID).ToList();

            foreach (var record in transaction.Recordes)
            {
                user.Cart.Records.Remove(record);
                record.Quantity = cart.Records.FirstOrDefault(r => r.RecordID == record.RecordID).Quantity;
                record.Cart = null;
                record.CartID = null;
                
            }
            db.Payments.Add(transaction.Payment);
            db.Transactions.Add(transaction);
            db.SaveChanges();

            return RedirectToAction("Details/"+ transaction.TransactionID);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PayTransaction(Payment payment)
        {
            var oldPay = db.Payments
                .FirstOrDefault(p => p.PaymentID == payment.PaymentID);

            oldPay.PaymentMethod = payment.PaymentMethod;
            oldPay.status = PaymentStatus.Paid;
            //oldPay.status = PaymentStatus.Processing;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult WithdrawTransaction(Payment payment)
        //{
        //    var oldPay = db.Payments.FirstOrDefault(p => p.PaymentID == payment.PaymentID);

        //    oldPay.PaymentMethod = payment.PaymentMethod;
        //    oldPay.status = PaymentStatus.Processing;

        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

    }
}

Online_book_shopping/Online_book_shopping/Views/Transactions/Create.cshtml
@model Online_book_shopping.Models.Transaction

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TransactionID, "TransactionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TransactionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TransactionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShippingStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ShippingStatus, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShippingStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Online_book_shopping/Online_book_shopping/Views/Transactions/Delete.cshtml
@model Online_book_shopping.Models.Transaction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Payment.PaymentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment.PaymentID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShippingStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShippingStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Online_book_shopping/Online_book_shopping/Views/Transactions/Details.cshtml
@model Online_book_shopping.Models.Transaction

<script>
    function Withdraw(event, id)
    {
        //alert("Withdraw?");
        if (confirm('Withdraw?')) {
            $.ajax({
                type: "POST",
                url: "/Transactions/Delete",
                data: { id: id },
                success: function (data) {
                    //alert("Removed");
                    //location.reload();
                    top.location.href = '/Transactions/Index';
                }
            });
        } else {
        }

    };
</script>

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<h4>Transaction</h4>

<div class="list-group">
    @foreach (var record in Model.Recordes)
    {
        <div class="row list-group-item">
            @Html.Partial("~/Views/Cart/ListOfRecordCart.cshtml", record)
        </div>
    }
</div>
    <div class="row">
        <h4>
            @Html.DisplayNameFor(model => model.ShippingStatus)
            :
            <b>@Html.DisplayFor(model => model.ShippingStatus)</b>
        </h4>
            @if (Model.ShippingStatus == Online_book_shopping.Models.ShippingStatus.Processing)
            {
                @*@Html.ActionLink("Withdraw", "DeleteConfirmed/"+@Model.TransactionID)
                <span onclick="Withdraw(event,@Model.TransactionID )" class="glyphicon glyphicon-remove" style="font-size: 2em"></span>*@
                <a onclick="Withdraw(event,@Model.TransactionID )">
                    <h6>Withdraw</h6>
                    
                </a>
            }
        
    </div>
    <div class="row">
        <h4>
            @Html.DisplayNameFor(model => model.Total)
            : $
            <b>@Html.DisplayFor(model => model.Total)</b>
        </h4>
    </div>
<br />
    @Html.Partial("~/Views/Transactions/PaymentPartial.cshtml", Model.Payment)

    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>

Online_book_shopping/Online_book_shopping/Views/Transactions/Edit.cshtml
@model Online_book_shopping.Models.Transaction

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TransactionID)

        <div class="form-group">
            @Html.LabelFor(model => model.ShippingStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ShippingStatus, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShippingStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Online_book_shopping/Online_book_shopping/Views/Transactions/Index.cshtml
@model IEnumerable<Online_book_shopping.Models.Transaction>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Payment.status)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Payment.PaymentMethod )
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShippingStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Payment.status)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Payment.PaymentMethod )
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShippingStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.TransactionID })*@
            @Html.ActionLink("Details", "Details", new { id=item.TransactionID })
            @*@Html.ActionLink("Delete", "Delete", new { id=item.TransactionID })*@
        </td>
    </tr>
}

</table>

Online_book_shopping/Online_book_shopping/Views/Transactions/PaymentPartial.cshtml
@model Online_book_shopping.Models.Payment
@using Online_book_shopping.Models

@if (Model.status == PaymentStatus.Unpaid)

{
    using (Html.BeginForm("PayTransaction", "Transactions", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">        
            <h4><b>Payment</b></h4>
            
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.PaymentID)

            <div class="form-group">
                @Html.LabelFor(model => model.PaymentMethod, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.PaymentMethod, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PaymentMethod, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Pay" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

}

else
{

        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Payment</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.PaymentID)

            <div class="form-group">
                @Html.LabelFor(model => model.PaymentMethod, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.DisplayFor(model => model.PaymentMethod)
                </div>
            </div>

            <div class="form-group">
                    @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">

                        @Html.DisplayFor(model => model.status)

                    </div>
                </div>
        </div>
}